Traceback (most recent call last):
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 618, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/Users/will/miniforge3/lib/python3.10/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/will/miniforge3/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/will/miniforge3/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 830, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 642, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Users/will/miniforge3/lib/python3.10/site-packages/nbclient/client.py", line 689, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
["freqs_model = np.loadtxt('../data/model_sed_freqs.txt').T", "I_models = np.loadtxt('../data/Algol_I_models.txt')", "V_models = np.loadtxt('../data/Algol_V_models.txt')", "freqs_obs, I_obs, sI_obs, V_obs, sV_obs = np.loadtxt('../data/Algol_data.txt', unpack=True)", '']
...
['samples /= np.array([1, 1, 1, 1, np.pi/180, np.pi/180])', "lmfit_params = np.loadtxt('../data/Algol_lmfit_params.txt')", 'lmfit_params /= np.array([1, 1, 1, 1, np.pi/180, np.pi/180])', '', "plt.style.use('../data/thermal-gs.mplstyle')"]
-------------------

